export const AGREGAR_ARTICULO = "AGREGAR_ARTICULO";
export const AGREGAR_ARTICULO_EXITO = "AGREGAR_ARTICULO_EXITO";
export const AGREGAR_ARTICULO_ERROR = "AGREGAR_ARTICULO_ERROR";

export const COMENZAR_DESCARGA_ARTICULOS = "COMENZAR_DESCARGA_ARTICULOS";
export const DESCARGA_ARTICULOS_EXITO = "DESCARGA_ARTICULOS_EXITO";
export const DESCARGA_ARTICULOS_ERROR = "DESCARGA_ARTICULOS_ERROR";

export const OBTENER_ARTICULO_ELIMINAR = "OBTENER_ARTICULO_ELIMINAR";
export const ARTICULO_ELIMINADO_EXITO = "ARTICULO_ELIMINADO_EXITO";
export const ARTICULO_ELIMINADO_ERROR = "ARTICULO_ELIMINADO_ERROR";

export const OBTENER_ARTICULO_EDITAR = "OBTENER_ARTICULO_EDITAR";
export const COMENZAR_EDICION_ARTICULO = "COMENZAR_EDICION_ARTICULO";
export const ARTICULO_EDITADO_EXITO = "ARTICULO_EDITADO_EXITO";
export const ARTICULO_EDITADO_ERROR = "ARTICULO_EDITADO_ERROR";

export const AGREGAR_ALBUM = "AGREGAR_ALBUM";
export const AGREGAR_ALBUM_EXITO = "AGREGAR_ALBUM_EXITO";
export const AGREGAR_ALBUM_ERROR = "AGREGAR_ALBUM_ERROR";

export const CARGAR_FOTOS_ALBUM = "CARGAR_FOTOS_ALBUM";
export const CARGAR_FOTOS_ALBUM_EXITO = "CARGAR_FOTOS_ALBUM_EXITO";
export const CARGAR_FOTOS_ALBUM_ERROR = "CARGAR_FOTOS_ALBUM_ERROR";

export const COMENZAR_DESCARGA_ALBUM = "COMENZAR_DESCARGA_ALBUM";
export const DESCARGA_ALBUM_EXITO = "DESCARGA_ALBUM_EXITO";
export const DESCARGA_ALBUM_ERROR = "DESCARGA_ALBUM_ERROR";

export const OBTENER_ALBUM_ELIMINAR = "OBTENER_ALBUM_ELIMINAR";
export const ALBUM_ELIMINADO_EXITO = "ALBUM_ELIMINADO_EXITO";
export const ALBUM_ELIMINADO_ERROR = "ALBUM_ELIMINADO_ERROR";

export const OBTENER_ALBUM_EDITAR = "OBTENER_ALBUM_EDITAR";
export const COMENZAR_EDICION_ALBUM = "COMENZAR_EDICION_ALBUM";
export const ALBUM_EDITADO_EXITO = "ALBUM_EDITADO_EXITO";
export const ALBUM_EDITADO_ERROR = "ALBUM_EDITADO_ERROR";

export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";

export const AGREGAR_USUARIO = "AGREGAR_USUARIO";
export const AGREGAR_USUARIO_EXITO = "AGREGAR_USUARIO_EXITO";
export const AGREGAR_USUARIO_ERROR = "AGREGAR_USUARIO_ERROR";

export const COMENZAR_DESCARGA_USUARIO = "COMENZAR_DESCARGA_USUARIO";
export const DESCARGA_USUARIO_EXITO = "DESCARGA_USUARIO_EXITO";
export const DESCARGA_USUARIO_ERROR = "DESCARGA_USUARIO_ERROR";

export const OBTENER_USUARIO_ELIMINAR = "OBTENER_USUARIO_ELIMINAR";
export const USUARIO_ELIMINADO_EXITO = "USUARIO_ELIMINADO_EXITO";
export const USUARIO_ELIMINADO_ERROR = "USUARIO_ELIMINADO_ERROR";

export const OBTENER_USUARIO_EDITAR = "OBTENER_USUARIO_EDITAR";
export const COMENZAR_EDICION_USUARIO = "COMENZAR_EDICION_USUARIO";
export const USUARIO_EDITADO_EXITO = "USUARIO_EDITADO_EXITO";
export const USUARIO_EDITADO_ERROR = "USUARIO_EDITADO_ERROR";

export const AGREGAR_COMENTARIO = "AGREGAR_COMENTARIO";
export const AGREGAR_COMENTARIO_EXITO = "AGREGAR_COMENTARIO_EXITO";
export const AGREGAR_COMENTARIO_ERROR = "AGREGAR_COMENTARIO_ERROR";

export const COMENZAR_DESCARGA_COMENTARIO = "COMENZAR_DESCARGA_COMENTARIO";
export const DESCARGA_COMENTARIO_EXITO = "DESCARGA_COMENTARIO_EXITO";
export const DESCARGA_COMENTARIO_ERROR = "DESCARGA_COMENTARIO_ERROR";

export const OBTENER_COMENTARIO_ELIMINAR = "OBTENER_COMENTARIO_ELIMINAR";
export const COMENTARIO_ELIMINADO_EXITO = "COMENTARIO_ELIMINADO_EXITO";
export const COMENTARIO_ELIMINADO_ERROR = "COMENTARIO_ELIMINADO_ERROR";

export const OBTENER_COMENTARIO_EDITAR = "OBTENER_COMENTARIO_EDITAR";
export const COMENZAR_EDICION_COMENTARIO = "COMENZAR_EDICION_COMENTARIO";
export const COMENTARIO_EDITADO_EXITO = "COMENTARIO_EDITADO_EXITO";
export const COMENTARIO_EDITADO_ERROR = "COMENTARIO_EDITADO_ERROR";

export const AGREGAR_FOTO = "AGREGAR_FOTO";
export const AGREGAR_FOTO_EXITO = "AGREGAR_FOTO_EXITO";
export const AGREGAR_FOTO_ERROR = "AGREGAR_FOTO_ERROR";

export const COMENZAR_DESCARGA_FOTO = "COMENZAR_DESCARGA_FOTO";
export const DESCARGA_FOTO_EXITO = "DESCARGA_FOTO_EXITO";
export const DESCARGA_FOTO_ERROR = "DESCARGA_FOTO_ERROR";

export const OBTENER_FOTO_ELIMINAR = "OBTENER_FOTO_ELIMINAR";
export const FOTO_ELIMINADO_EXITO = "FOTO_ELIMINADO_EXITO";
export const FOTO_ELIMINADO_ERROR = "FOTO_ELIMINADO_ERROR";

export const OBTENER_FOTO_EDITAR = "OBTENER_FOTO_EDITAR";
export const COMENZAR_EDICION_FOTO = "COMENZAR_EDICION_FOTO";
export const FOTO_EDITADO_EXITO = "FOTO_EDITADO_EXITO";
export const FOTO_EDITADO_ERROR = "FOTO_EDITADO_ERROR";

export const CARGAR_RELACION_TABLAS = "CARGAR_RELACION_TABLAS";
export const CARGAR_RELACION_TABLAS_EXITO = "CARGAR_RELACION_TABLAS_EXITO";
export const CARGAR_RELACION_TABLAS_ERROR = "CARGAR_RELACION_TABLAS_ERROR";

export const CARGAR_RELACION_TABLASDOS = "CARGAR_RELACION_TABLASDOS";
export const CARGAR_RELACION_TABLAS_EXITODOS =
  "CARGAR_RELACION_TABLAS_EXITODOS";
export const CARGAR_RELACION_TABLAS_ERRORDOS =
  "CARGAR_RELACION_TABLAS_ERRORDOS";

export const COMENZAR_EDICION_RELACION_TABLAS =
  "COMENZAR_EDICION_RELACION_TABLAS";
export const OBTENER_RELACION_TABLAS_EDITAR = "OBTENER_RELACION_TABLAS_EDITAR";
export const RELACION_TABLAS_EDITADO_EXITO = "RELACION_TABLAS_EDITADO_EXITO";
export const RELACION_TABLAS_EDITADO_ERROR = "RELACION_TABLAS_EDITADO_ERROR";

export const AGREGAR_TABLA = "AGREGAR_TABLA";
export const AGREGAR_TABLA_EXITO = "AGREGAR_TABLA_EXITO";
export const AGREGAR_TABLA_ERROR = "AGREGAR_TABLA_ERROR";

export const COMENZAR_DESCARGA_TABLA = "COMENZAR_DESCARGA_TABLA";
export const DESCARGA_TABLA_EXITO = "DESCARGA_TABLA_EXITO";
export const DESCARGA_TABLA_ERROR = "DESCARGA_TABLA_ERROR";

export const OBTENER_TABLA_ELIMINAR = "OBTENER_TABLA_ELIMINAR";
export const TABLA_ELIMINADO_EXITO = "TABLA_ELIMINADO_EXITO";
export const TABLA_ELIMINADO_ERROR = "TABLA_ELIMINADO_ERROR";

export const OBTENER_TABLA_EDITAR = "OBTENER_TABLA_EDITAR";
export const COMENZAR_EDICION_TABLA = "COMENZAR_EDICION_TABLA";
export const TABLA_EDITADO_EXITO = "TABLA_EDITADO_EXITO";
export const TABLA_EDITADO_ERROR = "TABLA_EDITADO_ERROR";

export const ACTUALIZAR_TEXTO = "AGREGAR_TEXTO";
export const ESTABLECER_VIEW_LIST = "ESTABLECER_VIEW_LIST";
export const ESTABLECER_ACTIVE_CODE = "ESTABLECER_ACTIVE_CODE";
export const AGREGAR_CODE = "AGREGAR_CODE";
